version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - DEEPINFRA_API_KEY=${DEEPINFRA_API_KEY:-}
      - DEEPINFRA_MODEL=meta-llama/Meta-Llama-3.1-70B-Instruct

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
