name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black

      - name: Ruff (lint)
        run: ruff check .

      - name: Black (auto format)
        run: black .

  smoke:
    runs-on: ubuntu-latest
    needs: checks
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt uvicorn[standard]

      - name: Start API (background)
        run: |
          ls data || true           
          uvicorn app.main:app --port 8000 --app-dir . > uvicorn.log 2>&1 &
          echo $! > uvicorn.pid
          sleep 2                   

      - name: Hit /health
        run: |
          curl -f http://127.0.0.1:8000/api/v1/health
          echo "---- uvicorn.log ----"
          cat uvicorn.log

      - name: Stop API
        if: always()
        run: |
          kill "$(cat uvicorn.pid)" || true
          sleep 1 || true
          pkill -f uvicorn || true
